services:
  web:
    build: .
    container_name: casebuddy
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./data/db:/app/data/db  # For SQLite database
      - ./data/logs:/app/data/logs  # Added logs volume
    ports:
      - "8030:8000"  # Changed port to avoid conflict with your other project
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - ALLOWED_HOSTS=localhost,127.0.0.1,casebuddy.srshti.co.in,hskow8kgwsw4ww0kk844c8c8.82.112.235.216.sslip.io
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=sqlite:///data/db/db.sqlite3
      - PYTHONUNBUFFERED=1
      # Email settings (optional)
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

volumes:
  static_volume:
  media_volume: 