# Generated by Django 5.1.6 on 2025-02-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_case_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('CIVIL', 'Civil Case'), ('CRIMINAL', 'Criminal Case'), ('FAMILY', 'Family Law'), ('CORPORATE', 'Corporate Law'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='client_draft',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lawyer_draft',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CaseQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_age', models.IntegerField()),
                ('client_address', models.TextField()),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=200)),
                ('incident_description', models.TextField()),
                ('witnesses', models.TextField(blank=True)),
                ('previous_legal_actions', models.TextField(blank=True)),
                ('desired_outcome', models.TextField()),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='app.case')),
            ],
        ),
    ]
