# Generated by Django 5.1.6 on 2025-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_case_case_type_case_client_draft_case_lawyer_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casequestionnaire',
            name='case_number',
            field=models.CharField(blank=True, help_text='If any previous case number exists', max_length=50),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='court_jurisdiction',
            field=models.CharField(blank=True, help_text='Specify the court where the case will be filed', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='defendant_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='defendant_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='casequestionnaire',
            name='defendant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casequestionnaire',
            name='witnesses',
            field=models.TextField(blank=True, help_text="Enter each witness's name, address, and contact information"),
        ),
    ]
